[Details]
  Icon = "Icon.png"
  Name = "gofoom Editor"
  ID = "com.foom.editor"
  Version = "0.5.0"
  Build = 2

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"

[LinuxAndBSD]
  GenericName = "gofoom Editor"
  Categories = ["Games"]
  Comment = "The world editor for the gofoom engine"
  Keywords = ["editor", "gofoom"]
